[package]
name = "leopold"
version = "0.0.1"
authors = ["quicksilver.machine@gmail.com"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
bollard = "0.4"
futures = "0.3.5"
tokio = {version="0.2.21", features = ["full"]}
