[package]
name = "leopold"
version = "0.0.1"
authors = ["quicksilver.machine@gmail.com"]
edition = "2018"

[dependencies]
bollard = "0.4"
futures = "0.3.5"
structopt = "0.3"
tokio = {version="0.2.21", features = ["full"]}
