# App configuration example

tasks:
  list_containers:
    - id: DockerContainerList
      command:
        description: List docker containers
  install:
    - id: DockerImagePull
      command:
        description: Pull docker image
        name: nginx
        version: latest
    - id: DockerImageList
      command:
        description: List docker images
  docker_version:
    - id: DockerVersion
      command:
        description: Display docker engine version
  create_container:
    - id: DockerContainerCreate
      command:
        description: New container
        image: nginx:<<image_version>>
        name: container_name
        mounts: []
        ports:
          - host: 127.0.0.1
            internal_port: 80/tcp
            external_ports:
              - 0/tcp
  remove_container:
    - id: DockerContainerRemove
      command:
        description: Remove container
        name: container_name
  start_container:
    - id: DockerContainerStart
      command:
        name: container_name
  stop_container:
    - id: DockerContainerStop
      command:
        name: container_name
  restart_container:
    - id: DockerContainerRestart
      command:
        name: container_name
  sleep:
    - id: Sleep
      command:
        description: Sleep for specified number of seconds
        duration: 5
  test_inheritance:
    - list_containers
    - docker_version
  test_inheritance_nested:
    - test_inheritance
  test_inheritance_nested_deep:
    - test_inheritance_nested
