extends:
  - master
tasks:
  install:
    - id: DockerImagePull
      command:
        description: Pull docker image
        name: nginx
        version: latest
    - id: DockerImageList
      command:
        description: List docker images
  docker_version:
    - id: DockerEngineVersion
      command:
        description: Display docker engine version
