extends:
  - master
tasks:
  install:
    - command: DockerImagePull
      parameters:
        description: Pull docker image
        args:
          - nginx
          - latest
        kwargs1: {}
    - command: DockerImageList
      parameters:
        description: List docker images
        args: []
        kwargs2: {}
  docker_version:
    - command: DockerEngineVersion
      parameters:
        description: Display docker engine version
        args: []
        kwargs3: {}
